version: '3'
services:
  web:
    image: faguim/harena-asm:v0.1.0
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      - SOLR_HOST=solr
    depends_on:
      - solr
    container_name: harena-asm



  solr:
    image: solr
    ports:
      - "8983:8983"
    # volumes:
    #  - ./solr/:/var/solr/
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - pmc4
    container_name: harena-solr

