version: '3'
services:
  web:
    image: harena-asm:latest
    ports:
      - "5000:5000"
    environment:
      - SOLR_HOST=solr
    depends_on:
      - solr
    container_name: harena-asm


  solr:
    image: solr
    ports:
      - "8983:8983"
    volumes:
      - data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - pmc
    container_name: harena_solr

volumes:
  data:

