version: '3'
services:
  web:
    build: .
    image: asm:v0.0.1
    ports:
      - "5000:5000"
    environment:
      - SOLR_HOST=solr
    volumes:
      - ../:/app
    depends_on:
      - solr
    container_name: harena_asm


  solr:
    image: solr
    ports:
      - "8983:8983"
    volumes:
      - data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - pmc
    container_name: solr

volumes:
  data:

